// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Reservation struct {
	ID          int64
	UserID      int64
	RoomID      int64
	StartTime   time.Time
	EndTime     time.Time
	Status      string
	GcalEventID sql.NullString
}

type Room struct {
	ID   int64
	Name string
}

type User struct {
	ID    int64
	Email string
	Name  string
	Role  string
}
