// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, room_id, start_time, end_time, status, gcal_event_id)
VALUES (
	$1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, room_id, start_time, end_time, status, gcal_event_id
`

type CreateReservationParams struct {
	UserID      int64
	RoomID      int64
	StartTime   time.Time
	EndTime     time.Time
	Status      string
	GcalEventID sql.NullString
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.UserID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.GcalEventID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.GcalEventID,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, user_id, room_id, start_time, end_time, status, gcal_event_id FROM reservations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReservation(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.GcalEventID,
	)
	return i, err
}

const listReservationsByRoom = `-- name: ListReservationsByRoom :many
SELECT id, user_id, room_id, start_time, end_time, status, gcal_event_id FROM reservations
WHERE room_id = $1
ORDER BY start_time ASC
`

func (q *Queries) ListReservationsByRoom(ctx context.Context, roomID int64) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listReservationsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.GcalEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
