// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, room_id, start_time, end_time, status)
VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, user_id, room_id, start_time, end_time, status, gcal_event_id
`

type CreateReservationParams struct {
	UserID    int64
	RoomID    int64
	StartTime time.Time
	EndTime   time.Time
	Status    string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.UserID,
		arg.RoomID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.GcalEventID,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations
WHERE id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReservation, id)
	return err
}

const existsOverlappingReservation = `-- name: ExistsOverlappingReservation :one
SELECT EXISTS (
    SELECT 1
    FROM reservations
    WHERE room_id = $1
      AND start_time < $2
      AND end_time > $3
	FOR UPDATE
) AS overlap
`

type ExistsOverlappingReservationParams struct {
	RoomID    int64
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) ExistsOverlappingReservation(ctx context.Context, arg ExistsOverlappingReservationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsOverlappingReservation, arg.RoomID, arg.StartTime, arg.EndTime)
	var overlap bool
	err := row.Scan(&overlap)
	return overlap, err
}

const getAllBetweenDates = `-- name: GetAllBetweenDates :many
SELECT 
    r.id,
    r.room_id,
    r.start_time,
    r.end_time,
    r.user_id as created_by_id,
    u.name as created_by_name,
    room.name as room_name
FROM reservations r
INNER JOIN users u ON r.user_id = u.id
INNER JOIN rooms room ON r.room_id = room.id
WHERE r.start_time >= $1
  AND r.end_time <= $2
ORDER BY r.room_id, r.start_time
`

type GetAllBetweenDatesParams struct {
	StartTime time.Time
	EndTime   time.Time
}

type GetAllBetweenDatesRow struct {
	ID            int64
	RoomID        int64
	StartTime     time.Time
	EndTime       time.Time
	CreatedByID   int64
	CreatedByName string
	RoomName      string
}

func (q *Queries) GetAllBetweenDates(ctx context.Context, arg GetAllBetweenDatesParams) ([]GetAllBetweenDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBetweenDates, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBetweenDatesRow
	for rows.Next() {
		var i GetAllBetweenDatesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT id, user_id, room_id, start_time, end_time, status, gcal_event_id FROM reservations
WHERE id = $1
`

func (q *Queries) GetReservationByID(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.GcalEventID,
	)
	return i, err
}

const listReservationsByRoom = `-- name: ListReservationsByRoom :many
SELECT id, user_id, room_id, start_time, end_time, status, gcal_event_id FROM reservations
WHERE room_id = $1
ORDER BY start_time ASC
`

func (q *Queries) ListReservationsByRoom(ctx context.Context, roomID int64) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listReservationsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.GcalEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoogleCalID = `-- name: UpdateGoogleCalID :exec
UPDATE reservations
SET gcal_event_id = $2
WHERE id = $1
`

type UpdateGoogleCalIDParams struct {
	ID          int64
	GcalEventID sql.NullString
}

func (q *Queries) UpdateGoogleCalID(ctx context.Context, arg UpdateGoogleCalIDParams) error {
	_, err := q.db.ExecContext(ctx, updateGoogleCalID, arg.ID, arg.GcalEventID)
	return err
}
