// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
)

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
