spring:
  application:
    name: book-me
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_EMAIL}
            client-secret: ${GOOGLE_PRIVATE_KEY}
            scope:
              - https://www.googleapis.com/auth/calendar
          42-intra:
            client-id: ${CLIENT_ID}
            client-secret: ${SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTH_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            calendar-uri: ${GOOGLE_CALENDER_URI}
            calendar-id: ${GOOGLE_CALENDER_ID}
          42-intra:
            authorization-uri: ${OAUTH_AUTH_URI}
            user-info-uri: ${USER_INFO_URL}
            token-uri:  ${OAUTH_TOKEN_URI}
  Jwt:
    secret: ${JWT_SECRET}
    refreshToken: 3600
  GoogleJwt:
    tokenExpiration: 3600
  profiles:
    active: dev
  redirect:
    token_url: ${REDIRECT_TOKEN_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL_USERNAME}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  from: #Email Sender
    email: ${FROM_EMAIL}
