spring:
  application:
    name: book-me
  config:
    import: optional:file:.env.yaml
  security:
    oauth2:
      client:
        registration:
          42-intra:
            client-id: ${FORTY_TWO.CLIENT_ID}
            client-secret: ${FORTY_TWO.SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${FORTY_TWO.REDIRECT_URI}
        provider:
          42-intra:
            authorization-uri: ${FORTY_TWO.OAUTH_AUTH_URI}
            token-uri:  ${FORTY_TWO.OAUTH_TOKEN_URI}
  Jwt:
    secret: ${JWT_SECRET}
    refreshToken: 3600
  profiles:
    active: dev