spring:
  config:
    import: optional:file:.env.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/bookMe?createDatabaseIfNotExist=true
    username: root
    password: mysqldb
  jpa:
    show-sql: true