spring:
  application:
    name: book-me
  config:
    import: optional:file:.env.yaml
  security:
    oauth2:
      client:
        registration:
          42-intra:
            client-id: ${FORTY_TWO.CLIENT_ID}
            client-secret: ${FORTY_TWO.SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${FORTY_TWO.REDIRECT_URI}
        provider:
          42-intra:
            authorization-uri: ${FORTY_TWO.OAUTH_AUTH_URI}
            token-uri:  ${FORTY_TWO.OAUTH_TOKEN_URI}
  Jwt:
    secret: ${JWT_SECRET}
    refreshToken: 3600
  profiles:
    active: dev
  redirect:
    token_url: ${REDIRECT_TOKEN_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL_USERNAME}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  from: #Email Sender
    email: ${FROM_EMAIL}