-- +goose Up
CREATE TABLE users ( -- USERS
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS users;